FROM python:3.7-slim

ADD requirements.txt /
RUN pip install -r requirements.txt

ADD . /app
WORKDIR /app

ENTRYPOINT ["/app/docker/entry.sh"]
# CMD ["gunicorn", "-b", "0.0.0.0:8000, "FinalDjangoStaticNginx.wsgi"]
