version: '3.5'

services:
  django:
    build:
      context: ..
      dockerfile: docker/Dockerfile-django
    volumes:
      - Static:/tmp/volume

  nginx:
    build:
      context: ..
      dockerfile: docker/Dockerfile-nginx
    volumes:
      - Static:/volume
    ports:
      - 8000:80

  front:
    build:
      context: ..
      dockerfile: docker/Dockerfile-front
    volumes:
      - Static:/volume


volumes:
  Static:
